<Project>
  <PropertyGroup Condition="'$(IsPackable)' == 'true'">
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup Condition="'$(IsPackable)' == 'true'">
    <None Include="$(MSBuildProjectDirectory)/README.md" Pack="true" PackagePath="/" />
    <None Include="$(MSBuildThisFileDirectory)NOTICE.md" Pack="true" PackagePath="/" />
    <None Include="$(MSBuildThisFileDirectory)LICENSE" Pack="true" PackagePath="/" />
    <None Include="$(MSBuildThisFileDirectory)LICENSES/*" Pack="true" PackagePath="LICENSES/" />
  </ItemGroup>
</Project>
