import copy
import json
from pathlib import Path
import sys
import tempfile
import unittest
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from verify_upstream import DSH, MATRIX, ORIGIN, SKIPPABLE, aggregate, validate_report


class UpstreamGateTests(unittest.TestCase):
    def reports(self):
        # External discovery/report fixtures. The expected partition is explicit,
        # not generated by the planner being verified.
        matrix = [["composition", MATRIX, f"matrix > case {i}", 0] for i in range(8)]
        other = ["core", "core.spec.ts", "ordinary case", 0]
        inventory = sorted([*matrix, other, list(SKIPPABLE)])
        reports = []
        for shard, indices in ((1, (0, 4)), (2, (1, 5)), (3, (2, 6)), (4, (3, 7))):
            outcomes = [{"case": matrix[i], "status": "passed"} for i in indices]
            if shard == 1:
                outcomes += [{"case": other, "status": "passed"}, {"case": list(SKIPPABLE), "status": "skipped"}]
            reports.append({"shard": shard, "shards": 4, "status": "passed", "sourceUnchanged": True,
                            "identity": {"commit": "revision", "platform": "Windows", "dsh": DSH,
                                         "origin": ORIGIN, "node": "v24.12.0", "sourceSha256": {"config": "digest"}},
                            "inventory": inventory, "outcomes": outcomes, "steps": []})
        return reports

    def merge(self, reports):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            for index, report in enumerate(reports):
                path = root / str(index)
                path.mkdir()
                (path / "result.json").write_text(json.dumps(report), encoding="utf-8")
            # Stand in for the external approved suite-count inventory, not for
            # discovery, partitioning, execution outcomes or validation logic.
            counts = {("composition", MATRIX): 8, ("core", "core.spec.ts"): 1, SKIPPABLE[:2]: 1}
            with patch("verify_upstream.fixed_counts", return_value=counts):
                return aggregate(root, "revision", "Windows")

    def test_complete_union_preserves_explicit_capability_skip(self):
        result = self.merge(self.reports())
        self.assertEqual((result["cases"], result["passed"]), (10, 9))
        self.assertEqual(result["skipped"], [{"case": list(SKIPPABLE), "status": "skipped"}])

    def test_missing_duplicate_failed_or_drifting_shard_cannot_pass(self):
        mutations = [
            lambda r: r.pop(),
            lambda r: r.__setitem__(3, copy.deepcopy(r[0])),
            lambda r: r[0].update(status="failed"),
            lambda r: r[0].update(sourceUnchanged=False),
            lambda r: r[0]["identity"].update(commit="another revision"),
            lambda r: r[0]["identity"].update(platform="Linux"),
            lambda r: r[1]["identity"].update(node="different toolchain"),
            lambda r: r[1].update(inventory=r[1]["inventory"][:-1]),
        ]
        for mutate in mutations:
            with self.subTest(mutation=mutations.index(mutate)):
                reports = copy.deepcopy(self.reports())
                mutate(reports)
                with self.assertRaises(ValueError):
                    self.merge(reports)

    def test_missing_duplicate_misplaced_failed_and_skipped_cases_cannot_pass(self):
        mutations = [
            lambda r: r[1]["outcomes"].pop(),
            lambda r: r[1]["outcomes"].append(copy.deepcopy(r[1]["outcomes"][0])),
            lambda r: r[1]["outcomes"].append(r[2]["outcomes"].pop()),
            lambda r: r[1]["outcomes"][0].update(status="failed"),
            lambda r: r[1]["outcomes"][0].update(status="skipped"),
        ]
        for mutate in mutations:
            with self.subTest(mutation=mutations.index(mutate)):
                reports = self.reports()
                mutate(reports)
                with self.assertRaises(ValueError):
                    self.merge(reports)

    def test_identical_incomplete_discovery_in_every_shard_cannot_pass(self):
        reports = self.reports()
        omitted = ["core", "core.spec.ts", "ordinary case", 0]
        for report in reports:
            report["inventory"] = [case for case in report["inventory"] if case != omitted]
            report["outcomes"] = [row for row in report["outcomes"] if row["case"] != omitted]
        with self.assertRaisesRegex(ValueError, "fixed original suite inventory"):
            self.merge(reports)

    def test_vitest_filter_exclusions_are_not_counted_as_executed_cases(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            tests = [{"ancestorTitles": ["matrix"], "title": f"case {i}", "failureMessages": [],
                      "status": status} for i, status in enumerate(("passed", "skipped"))]
            report = {"success": True, "numFailedTests": 0, "numTotalTests": 2,
                      "numPassedTests": 1, "numPendingTests": 1,
                      "testResults": [{"name": str(root / MATRIX), "status": "passed", "assertionResults": tests}]}
            keys = {("composition", MATRIX, f"matrix > case {i}", 0) for i in range(2)}
            selected = {("composition", MATRIX, "matrix > case 0", 0)}
            self.assertEqual(validate_report(report, "composition", root, keys, selected), [
                {"case": ["composition", MATRIX, "matrix > case 0", 0], "status": "passed"}])
            mutations = [
                lambda r: r["testResults"][0]["assertionResults"].pop(),
                lambda r: r["testResults"][0]["assertionResults"].append(copy.deepcopy(tests[0])),
                lambda r: r["testResults"][0]["assertionResults"][0].update(status="skipped"),
                lambda r: r["testResults"][0]["assertionResults"][1].update(status="passed"),
                lambda r: r.update(numPassedTests=2),
                lambda r: r.update(numRuntimeErrorTestSuites=1),
                lambda r: r["testResults"][0].update(name=str(root.parent / "outside.spec.ts")),
            ]
            for mutate in mutations:
                with self.subTest(mutation=mutations.index(mutate)):
                    changed = copy.deepcopy(report)
                    mutate(changed)
                    with self.assertRaises(ValueError):
                        validate_report(changed, "composition", root, keys, selected)

    def test_identically_named_parameter_cases_keep_their_multiplicity(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            test = {"ancestorTitles": ["parameters"], "title": "undefined", "failureMessages": [], "status": "passed"}
            report = {"success": True, "numFailedTests": 0, "numTotalTests": 2,
                      "numPassedTests": 2, "numPendingTests": 0,
                      "testResults": [{"name": str(root / "parameters.spec.ts"), "status": "passed",
                                       "assertionResults": [test, copy.deepcopy(test)]}]}
            keys = {("composition", "parameters.spec.ts", "parameters > undefined", index) for index in (0, 1)}
            outcomes = validate_report(report, "composition", root, keys, keys)
            self.assertEqual([row["case"][3] for row in outcomes], [0, 1])
            report["testResults"][0]["assertionResults"].pop()
            report.update(numTotalTests=1, numPassedTests=1)
            with self.assertRaisesRegex(ValueError, "complete expected"):
                validate_report(report, "composition", root, keys, keys)


if __name__ == "__main__":
    unittest.main()
