using System.Text;
using System.Text.Json;
using System.Xml.Linq;
using Microsoft.CodeAnalysis.CSharp;

namespace Cordis.Typert.Generator.Model;

internal sealed class DotnetProjectionEmitter
{
    private readonly NativeModelDocument model;
    private readonly string client;
    private readonly Dictionary<string, NativeTypeDeclaration> declarations;
    private readonly HashSet<string> reachable = new(StringComparer.Ordinal);
    private readonly StringBuilder output = new();

    private DotnetProjectionEmitter(NativeModelDocument model, string client)
    {
        this.model = model;
        this.client = Identifier(client);
        declarations = model.Types.ToDictionary(type => type.Id, StringComparer.Ordinal);
    }

    internal static string Emit(NativeModelDocument model, string targetNamespace, string service, string client)
    {
        if (targetNamespace.Split('.').Any(part => !SyntaxFacts.IsValidIdentifier(part)))
            throw new InvalidDataException("Caller namespace must contain valid C# identifiers.");
        var emitter = new DotnetProjectionEmitter(model, client);
        return emitter.Generate(targetNamespace, service);
    }

    private string Generate(string targetNamespace, string service)
    {
        var selected = model.Services.SingleOrDefault(value => value.Key == service || value.SourceType == service) ??
            throw new InvalidDataException($"No unique native service '{service}'.");
        if (selected.Serializer is null)
            throw new InvalidDataException("Native caller projection requires an explicit source JSON context.");
        if (selected.Methods.Length == 0)
            throw new InvalidDataException("Selected service contains no authored Remote methods.");
        if (selected.Methods.Any(method => string.IsNullOrEmpty(method.Name)))
            throw new InvalidDataException("Remote method names must be non-empty caller identifiers.");
        if (selected
                .Methods.Select(method => char.ToUpperInvariant(method.Name[0]) + method.Name[1..] + "Async")
                .Distinct(StringComparer.Ordinal)
                .Count() != selected.Methods.Length)
            throw new InvalidDataException("Remote names collide after normalization to caller Async method names.");
        foreach (var method in selected.Methods)
        {
            if (method.Stream || method.Context is not null ||
                method.Parameters.Any(parameter => parameter.Lookup is not null) ||
                method.ReturnWrapper != "System.Threading.Tasks.Task<TResult>" ||
                method.Parameters.Any(parameter =>
                    parameter.RefKind != "None" || parameter.Optional || parameter.Params))
                throw new InvalidDataException(
                    $"{method.Name}: caller projection supports only direct ordinary unary methods.");
            Visit(method.Result);
            foreach (var parameter in method.Parameters)
                Visit(parameter.Type);
        }

        var relevantIds = reachable.Append(selected.Serializer.Id).ToHashSet(StringComparer.Ordinal);
        var blockers = model
            .Diagnostics.Where(value => value.Category == "AnalysisUnsupported" ||
                value.Symbol is null || relevantIds.Any(id => value.Symbol.StartsWith(id, StringComparison.Ordinal)) ||
                value.Symbol == selected.SourceType || value.Symbol.StartsWith(
                    model.Compilation.AssemblyName + ":" + selected.SourceType,
                    StringComparison.Ordinal))
            .ToArray();
        if (blockers.Length != 0)
            throw new InvalidDataException(
                string.Join("\n", blockers.Select(value => value.Category + " " + value.Code + ": " + value.Message)));
        ValidateTypeNames(selected);
        output
            .AppendLine("// <auto-generated/>")
            .AppendLine("// Native model " + model.ContractIdentity)
            .AppendLine("#nullable enable")
            .AppendLine("using System.Net.Http;")
            .AppendLine("using System.Text.Json;")
            .AppendLine("using System.Text.Json.Serialization;")
            .AppendLine("using System.Text.Json.Serialization.Metadata;")
            .AppendLine("using System.Threading;")
            .AppendLine("using System.Threading.Tasks;")
            .AppendLine("namespace " + targetNamespace + ";");
        foreach (var id in reachable.Order(StringComparer.Ordinal))
            EmitType(declarations[id]);
        foreach (var method in selected.Methods)
            EmitEnvelopes(method);
        output.AppendLine(
            $$"""
              internal sealed class {{client}}Failure
              {
                  [JsonPropertyName("code")] public string Code { get; set; } = "";
                  [JsonPropertyName("message")] public string Message { get; set; } = "";
                  [JsonPropertyName("details")] public JsonElement? Details { get; set; }
              }
              """);
        EmitContext(selected);
        EmitClient(selected);
        return output.ToString();
    }

    private void ValidateTypeNames(NativeService service)
    {
        var names = new Dictionary<string, string>(StringComparer.Ordinal);

        void Reserve(string name, string origin)
        {
            var identifier = Identifier(name).TrimStart('@');
            if (names.TryGetValue(identifier, out var previous))
                throw new InvalidDataException(
                    $"Caller type names collide at '{identifier}': {previous} and {origin}.");
            names.Add(identifier, origin);
        }

        foreach (var id in reachable.Order(StringComparer.Ordinal))
            Reserve(declarations[id].Name, "data type " + id);
        Reserve(client, "generated client");
        Reserve(client + "Json", "generated data JSON context");
        Reserve(client + "CarrierJson", "generated carrier JSON context");
        Reserve(client + "Failure", "generated failure envelope");
        foreach (var method in service.Methods)
        {
            var prefix = EnvelopePrefix(method);
            Reserve(prefix + "Args", "generated arguments for Remote " + method.Name);
            Reserve(prefix + "Request", "generated request for Remote " + method.Name);
            Reserve(prefix + "Response", "generated response for Remote " + method.Name);
        }
    }

    private string EnvelopePrefix(NativeMethod method) => client + Identifier(method.Name).TrimStart('@');

    private void Visit(NativeTypeReference type)
    {
        if (type.Kind is "unsupported" or "object" || type.Rank > 1)
            throw new InvalidDataException(
                "Caller projection cannot represent type " + type.Name + " (" + type.Kind + ").");
        if (type.Nullability == "None" &&
            (type.Kind is "named" or "array" or "collection" || type.Name == "System_String"))
            throw new InvalidDataException(
                "Oblivious reference annotations are retained in the model but require an explicit nullable caller projection: " +
                type.Name);
        foreach (var argument in type.Arguments)
            Visit(argument);
        if (type.Kind != "named" || !reachable.Add(type.Name))
            return;
        if (!declarations.TryGetValue(type.Name, out var declaration))
            throw new InvalidDataException("Native model omits reachable declaration " + type.Name);
        if (declaration.Kind is not ("record" or "class") || declaration.BaseType is not null ||
            declaration.TypeArguments.Length != 0)
            throw new InvalidDataException(
                "Caller projection currently supports only non-generic ordinary data records/classes without data inheritance: " +
                type.Name);
        foreach (var member in declaration.Members)
        {
            if (member.WriteAccess == "none")
                throw new InvalidDataException(
                    "ProjectionUnsupported TYPM112: read-only wire member cannot be copied into a writable caller DTO: " +
                    declaration.Id + "." + member.Name);
            Visit(member.Type);
        }

        foreach (var constructor in declaration.Constructors)
            foreach (var parameter in constructor.Parameters)
                Visit(parameter.Type);
    }

    private void EmitType(NativeTypeDeclaration type)
    {
        var name = Identifier(type.Name);
        Docs(type.Documentation, filter: "type");
        foreach (var attribute in type.Attributes)
            EmitAttribute(attribute);
        output.AppendLine("public sealed " + type.Kind + " " + name).AppendLine("{");
        var constructor = Constructor(type);
        if (constructor is not null)
        {
            Docs(type.Documentation, "    ", "constructor");
            if (constructor.JsonConstructor)
                output.AppendLine("    [JsonConstructor]");
            if (constructor.SetsRequiredMembers)
                output.AppendLine("    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]");
            output
                .Append("    public ")
                .Append(name)
                .Append('(')
                .Append(
                    string.Join(
                        ", ",
                        constructor.Parameters.Select(parameter => ParameterAttributes(parameter.Attributes) +
                            TypeName(parameter.Type) + " " + Identifier(parameter.Name) +
                            (parameter.Optional ? " = " + Constant(parameter.Default!) : ""))))
                .AppendLine(")")
                .AppendLine("    {");
            foreach (var parameter in constructor.Parameters)
            {
                if (parameter.Member is null)
                    throw new InvalidDataException(
                        "Constructor parameter has no matching public data member: " + type.Id + "." + parameter.Name);
                output.AppendLine(
                    "        this." + Identifier(parameter.Member) + " = " + Identifier(parameter.Name) + ";");
            }

            output.AppendLine("    }");
        }

        foreach (var member in type.Members)
        {
            Docs(member.Documentation, "    ");
            if (member.Accessibility != "Public" || !member.Readable)
                throw new InvalidDataException(
                    "Standalone caller cannot project a non-public/unreadable data member: " + type.Id + "." +
                    member.Name);
            foreach (var attribute in member.Attributes.Where(value =>
                         value.Name != "System.Text.Json.Serialization.JsonPropertyNameAttribute"))
                EmitAttribute(attribute, "    ");
            output.AppendLine("    [JsonPropertyName(" + Literal(member.WireName) + ")]");
            output
                .Append("    public ")
                .Append(member.Required ? "required " : "")
                .Append(TypeName(member.Type))
                .Append(' ')
                .Append(Identifier(member.Name));
            if (member.Kind != "field")
                output.Append(" { get; ").Append(member.WriteAccess).Append("; }");
            if (member.Initializer is not null)
                output.Append(" = ").Append(Constant(member.Initializer)).Append(';');
            else if (member.Kind == "field")
                output.Append(" = default!;");
            else if (!member.Required)
                output.Append(" = default!;");
            output.AppendLine();
        }

        output.AppendLine("}");
    }

    private static NativeConstructor? Constructor(NativeTypeDeclaration type)
    {
        var marked = type.Constructors.Where(value => value.JsonConstructor).ToArray();
        if (marked.Length > 1 || marked.Any(value => value.Accessibility != "Public"))
            throw new InvalidDataException("Standalone caller supports one public JSON constructor: " + type.Id);
        if (marked.Length == 1)
            return marked[0];
        var publicConstructors = type.Constructors.Where(value => value.Accessibility == "Public").ToArray();
        return publicConstructors.FirstOrDefault(value => value.Parameters.Length == 0) ??
            (publicConstructors.Length == 1
                ? publicConstructors[0]
                : throw new InvalidDataException("Ambiguous or absent public data constructor: " + type.Id));
    }

    private void EmitEnvelopes(NativeMethod method)
    {
        var prefix = EnvelopePrefix(method);
        output.AppendLine("internal sealed class " + prefix + "Args").AppendLine("{");
        foreach (var parameter in method.Parameters)
        {
            foreach (var attribute in parameter.Attributes)
                EmitAttribute(attribute, "    ");
            output.AppendLine(
                "    [JsonPropertyName(" + Literal(parameter.Wire) +
                "), JsonIgnore(Condition = JsonIgnoreCondition.Never)] public " + TypeName(parameter.Type) + " " +
                Identifier(parameter.Name) + " { get; set; } = default!;");
        }

        output
            .AppendLine("}")
            .AppendLine("internal sealed class " + prefix + "Request")
            .AppendLine("{")
            .AppendLine(
                "    [JsonPropertyName(\"args\"), JsonIgnore(Condition = JsonIgnoreCondition.Never)] public " + prefix +
                "Args Args { get; set; } = new();")
            .AppendLine("}")
            .AppendLine("internal sealed class " + prefix + "Response")
            .AppendLine("{")
            .AppendLine("    [JsonPropertyName(\"ok\")] public bool Ok { get; set; }")
            .AppendLine(
                "    [JsonPropertyName(\"value\")] public " + TypeName(method.Result) +
                " Value { get; set; } = default!;")
            .AppendLine("    [JsonPropertyName(\"error\")] public " + client + "Failure? Error { get; set; }")
            .AppendLine("}");
    }

    private void EmitContext(NativeService service)
    {
        foreach (var attribute in service.Serializer!.Attributes.Where(value =>
                     value.Name == "System.Text.Json.Serialization.JsonSourceGenerationOptionsAttribute"))
        {
            if (attribute.NamedArguments.Any(value => value.Name == "Converters"))
                throw new InvalidDataException("Context converters require a separately supported projection.");
            var mode = attribute.NamedArguments.FirstOrDefault(value => value.Name == "GenerationMode")?.Value;
            if (mode is not null && mode.Json is not ("0" or "1"))
                throw new InvalidDataException(
                    "Caller requires metadata-capable JSON generation, not serialization-only mode.");
            if (attribute.NamedArguments.Any(value =>
                    value.Name == "PreferredObjectCreationHandling" && value.Value.Json != "0"))
                throw new InvalidDataException(
                    "Populate object creation semantics require a separately supported caller projection.");
        }

        foreach (var attribute in service.Serializer.Attributes.Where(value =>
                     value.Name == "System.Text.Json.Serialization.JsonSerializableAttribute"))
            if (attribute.NamedArguments.Any(value =>
                    value.Name == "GenerationMode" && value.Value.Json is not ("0" or "1")))
                throw new InvalidDataException(
                    "Per-type serialization-only metadata does not support a standalone caller decoder.");
        var options = service
            .Serializer.Attributes.Where(value =>
                value.Name == "System.Text.Json.Serialization.JsonSourceGenerationOptionsAttribute")
            .ToArray();
        foreach (var attribute in options)
            EmitAttribute(attribute);
        var roots = service
            .Methods.SelectMany(method => method.Parameters.Select(parameter => parameter.Type).Append(method.Result))
            .Select(type => type.Kind == "nullable" ? TypeName(type) : TypeName(type).TrimEnd('?'))
            .Concat(reachable.Select(id => Identifier(declarations[id].Name)))
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal);
        foreach (var root in roots)
            output.AppendLine("[JsonSerializable(typeof(" + root + "))]");
        output.AppendLine("public partial class " + client + "Json : JsonSerializerContext;");
        foreach (var attribute in options)
            EmitAttribute(attribute);
        foreach (var method in service.Methods)
        {
            var prefix = EnvelopePrefix(method);
            output
                .AppendLine("[JsonSerializable(typeof(" + prefix + "Request))]")
                .AppendLine("[JsonSerializable(typeof(" + prefix + "Response))]");
        }

        output.AppendLine("internal partial class " + client + "CarrierJson : JsonSerializerContext;");
    }

    private void EmitClient(NativeService service)
    {
        output.AppendLine(
            $$"""
              /// <summary>A generated direct unary client. The caller owns the supplied HttpClient.</summary>
              public sealed class {{client}} : global::System.IDisposable
              {
                  private readonly HttpClient httpClient;
                  private readonly global::System.Uri remoteBase;
                  private readonly CancellationTokenSource lifetime = new();
                  private int disposed;
                  public {{client}}(HttpClient borrowedClient, global::System.Uri remoteBase)
                  {
                      global::System.ArgumentNullException.ThrowIfNull(borrowedClient);
                      global::System.ArgumentNullException.ThrowIfNull(remoteBase);
                      if (!remoteBase.IsAbsoluteUri) throw new global::System.ArgumentException("Remote base must be absolute.", nameof(remoteBase));
                      httpClient = borrowedClient;
                      this.remoteBase = remoteBase;
                  }
                  private void CheckActive()
                  {
                      if (global::System.Threading.Volatile.Read(ref disposed) != 0)
                          throw new global::Cordis.Composition.RemoteError("gateway/internal", "The Remote contribution was withdrawn.");
                  }
                  public void Dispose()
                  {
                      if (global::System.Threading.Interlocked.Exchange(ref disposed, 1) == 0)
                          lifetime.Cancel();
                  }
              """);
        foreach (var method in service.Methods)
        {
            var apiName = Identifier(char.ToUpperInvariant(method.Name[0]) + method.Name[1..] + "Async");
            var prefix = EnvelopePrefix(method);
            var scope = "__cordis";
            while (method.Parameters.Any(parameter => parameter.Name.StartsWith(scope, StringComparison.Ordinal)))
                scope += "_";
            var token = method.Parameters.Any(parameter => parameter.Name == "cancellationToken")
                ? scope + "CancellationToken"
                : "cancellationToken";
            Docs(method.Documentation, "    ");
            output
                .Append("    public async Task<")
                .Append(TypeName(method.Result))
                .Append("> ")
                .Append(apiName)
                .Append('(')
                .Append(
                    string.Join(
                        ", ",
                        method.Parameters.Select(parameter =>
                            TypeName(parameter.Type) + " " + Identifier(parameter.Name))))
                .Append(method.Parameters.Length == 0 ? "" : ", ")
                .AppendLine("CancellationToken " + token + " = default)")
                .AppendLine("    {")
                .AppendLine("        this.CheckActive();")
                .AppendLine(
                    "        using var " + scope + "Lifetime = CancellationTokenSource.CreateLinkedTokenSource(" +
                    token + ", this.lifetime.Token);")
                .AppendLine("        try")
                .AppendLine("        {")
                .AppendLine(
                    "            var " + scope + "Request = new " + prefix + "Request { Args = new " + prefix +
                    "Args {")
                .AppendLine(
                    string.Join(
                        ",\n",
                        method.Parameters.Select(parameter =>
                            "                " + Identifier(parameter.Name) + " = " + Identifier(parameter.Name))))
                .AppendLine("            } };")
                .AppendLine(
                    "            var " + scope + "RequestMetadata = (JsonTypeInfo<" + prefix + "Request>)" + client +
                    "CarrierJson.Default.GetTypeInfo(typeof(" + prefix + "Request))!;")
                .AppendLine(
                    "            using var " + scope +
                    "Content = new ByteArrayContent(JsonSerializer.SerializeToUtf8Bytes(" + scope + "Request, " +
                    scope + "RequestMetadata));")
                .AppendLine(
                    "            " + scope +
                    "Content.Headers.ContentType = new global::System.Net.Http.Headers.MediaTypeHeaderValue(\"application/json\");")
                .AppendLine(
                    "            var " + scope +
                    "Url = new global::System.Uri(this.remoteBase.AbsoluteUri.TrimEnd('/') + \"/\" + " + Literal(
                        Uri.EscapeDataString(service.Namespace) + "/" + Uri.EscapeDataString(method.Name)) + ");")
                .AppendLine(
                    "            using var " + scope + "Response = await this.httpClient.PostAsync(" + scope + "Url, " +
                    scope + "Content, " + scope + "Lifetime.Token).ConfigureAwait(false);")
                .AppendLine("            this.CheckActive();")
                .AppendLine("            " + scope + "Lifetime.Token.ThrowIfCancellationRequested();")
                .AppendLine(
                    "            if (!" + scope +
                    "Response.IsSuccessStatusCode) throw new global::Cordis.Composition.RemoteError(\"gateway/protocol\", \"HTTP \" + (int)" +
                    scope + "Response.StatusCode);")
                .AppendLine(
                    "            var " + scope + "Json = await " + scope + "Response.Content.ReadAsStringAsync(" +
                    scope + "Lifetime.Token).ConfigureAwait(false);")
                .AppendLine("            this.CheckActive();")
                .AppendLine("            " + scope + "Lifetime.Token.ThrowIfCancellationRequested();")
                .AppendLine("            using var " + scope + "Document = JsonDocument.Parse(" + scope + "Json);")
                .AppendLine(
                    "            if (!" + scope + "Document.RootElement.TryGetProperty(\"ok\", out var " + scope +
                    "Ok) || " + scope +
                    "Ok.ValueKind is not (JsonValueKind.True or JsonValueKind.False)) throw new JsonException(\"Invalid Remote result envelope.\");")
                .AppendLine(
                    "            if (" + scope + "Ok.GetBoolean() && !" + scope +
                    "Document.RootElement.TryGetProperty(\"value\", out var " + scope +
                    "Value)) throw new JsonException(\"Remote result is missing its value.\");")
                .AppendLine(
                    "            var " + scope + "Metadata = (JsonTypeInfo<" + prefix + "Response>)" + client +
                    "CarrierJson.Default.GetTypeInfo(typeof(" + prefix + "Response))!;")
                .AppendLine(
                    "            var " + scope + "Result = JsonSerializer.Deserialize(" + scope + "Json, " + scope +
                    "Metadata) ?? throw new JsonException(\"Null Remote envelope.\");")
                .AppendLine("            this.CheckActive();")
                .AppendLine("            " + scope + "Lifetime.Token.ThrowIfCancellationRequested();")
                .AppendLine("            if (!" + scope + "Result.Ok)")
                .AppendLine("            {")
                .AppendLine(
                    "                var " + scope + "Failure = " + scope +
                    "Result.Error ?? throw new JsonException(\"Remote failure is missing its error.\");")
                .AppendLine(
                    "                throw new global::Cordis.Composition.RemoteError(" + scope + "Failure.Code, " +
                    scope + "Failure.Message, " + scope + "Failure.Details);")
                .AppendLine("            }");
            if (method.Result.Kind != "json" && !Nullable(method.Result))
                output.AppendLine(
                    "            if (" + scope +
                    "Document.RootElement.GetProperty(\"value\").ValueKind == JsonValueKind.Null) throw new JsonException(\"Non-null native result cannot be null.\");");
            output
                .AppendLine("            return " + scope + "Result.Value;")
                .AppendLine("        }")
                .AppendLine("        catch (global::System.Exception " + scope + "Error)")
                .AppendLine("        {")
                .AppendLine("            this.CheckActive();")
                .AppendLine("            if (" + scope + "Error is global::Cordis.Composition.RemoteError) throw;")
                .AppendLine(
                    "            throw new global::Cordis.Composition.RemoteError(" + token +
                    ".IsCancellationRequested ? \"gateway/cancelled\" : \"gateway/internal\", " + scope +
                    "Error.Message, innerException: " + scope + "Error);")
                .AppendLine("        }")
                .AppendLine("    }");
        }

        output.AppendLine("}");
    }

    private string TypeName(NativeTypeReference type)
    {
        var name = type.Kind switch
        {
            "primitive" => type.Name switch
            {
                "System_Boolean" => "bool",
                "System_Byte" => "byte",
                "System_SByte" => "sbyte",
                "System_Int16" => "short",
                "System_UInt16" => "ushort",
                "System_Int32" => "int",
                "System_UInt32" => "uint",
                "System_Int64" => "long",
                "System_UInt64" => "ulong",
                "System_Single" => "float",
                "System_Double" => "double",
                "System_Decimal" => "decimal",
                "System_Char" => "char",
                "System_String" => "string",
                _ => throw new InvalidDataException("Unsupported CLR primitive " + type.Name)
            },
            "json" => "JsonElement",
            "named" => Identifier(declarations[type.Name].Name),
            "nullable" => TypeName(type.Arguments.Single()).TrimEnd('?') + "?",
            "array" => TypeName(type.Arguments.Single()) + "[]",
            "collection" => "global::" + type.Name[..type.Name.IndexOf('<')] + "<" +
                string.Join(", ", type.Arguments.Select(TypeName)) + ">",
            _ => throw new InvalidDataException("Unsupported native type kind " + type.Kind)
        };
        return type.Nullability == "Annotated" && type.Kind is not ("nullable" or "json") &&
            (type.Kind is "named" or "array" or "collection" || type.Name == "System_String")
                ? name + "?"
                : name;
    }

    private static bool Nullable(NativeTypeReference type) =>
        type.Kind == "nullable" || type.Nullability == "Annotated";

    private static string Identifier(string value) => SyntaxFacts.IsValidIdentifier(value) ? value :
        SyntaxFacts.GetKeywordKind(value) != SyntaxKind.None ? "@" + value :
        throw new InvalidDataException("Invalid C# identifier " + value);

    private static string Literal(string value) =>
        Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, true);

    private static string Constant(NativeConstant value) => value.Kind switch
    {
        "emptyCollection" => "[]",
        "enum" => "(global::" + value.Type + ")" + value.Json,
        "type" => "typeof(" + JsonSerializer.Deserialize<string>(value.Json) + ")",
        "value" when value.Json == "null" => "null",
        "value" => value.Type.TrimEnd('?') switch
        {
            "string" or "System.String" => Literal(JsonSerializer.Deserialize<string>(value.Json)!),
            "char" or "System.Char" => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(
                JsonSerializer.Deserialize<string>(value.Json)![0],
                true),
            "float" or "System.Single" => value.Json + "F",
            "decimal" or "System.Decimal" => value.Json + "M",
            "ulong" or "System.UInt64" => value.Json + "UL",
            "long" or "System.Int64" => value.Json + "L",
            "uint" or "System.UInt32" => value.Json + "U",
            _ => value.Json
        },
        _ => throw new InvalidDataException("Unsupported projected constant kind " + value.Kind)
    };

    private void EmitAttribute(NativeAttribute attribute, string indent = "")
        => output.AppendLine(indent + AttributeText(attribute));

    private static string ParameterAttributes(NativeAttribute[] attributes) =>
        string.Concat(attributes.Select(attribute => AttributeText(attribute) + " "));

    private static string AttributeText(NativeAttribute attribute)
    {
        var supported = attribute.Name is "System.Text.Json.Serialization.JsonPropertyNameAttribute" or
            "System.Text.Json.Serialization.JsonIgnoreAttribute"
            or "System.Text.Json.Serialization.JsonRequiredAttribute" or
            "System.Text.Json.Serialization.JsonPropertyOrderAttribute"
            or "System.Text.Json.Serialization.JsonNumberHandlingAttribute" or
            "System.Text.Json.Serialization.JsonIncludeAttribute"
            or "System.Text.Json.Serialization.JsonSourceGenerationOptionsAttribute" or
            "System.Text.Json.Serialization.JsonUnmappedMemberHandlingAttribute" or
            "System.Diagnostics.CodeAnalysis.AllowNullAttribute"
            or "System.Diagnostics.CodeAnalysis.DisallowNullAttribute" or
            "System.Diagnostics.CodeAnalysis.MaybeNullAttribute" or "System.Diagnostics.CodeAnalysis.NotNullAttribute";
        if (!supported)
            throw new InvalidDataException(
                "JSON attribute requires an explicitly supported projection: " + attribute.Name);
        return "[global::" + attribute.Name + "(" + string.Join(
            ", ",
            attribute
                .Arguments.Select(Constant)
                .Concat(attribute.NamedArguments.Select(value => value.Name + " = " + Constant(value.Value)))) + ")]";
    }

    private void Docs(string xml, string indent = "", string? filter = null)
    {
        if (string.IsNullOrWhiteSpace(xml))
            return;
        var member = XElement.Parse(xml);
        foreach (var element in member.Elements())
        {
            if (filter == "type" && element.Name.LocalName == "param" ||
                filter == "constructor" && element.Name.LocalName != "param")
                continue;
            foreach (var line in element.ToString().Split('\n'))
                output.AppendLine(indent + "/// " + line.TrimEnd('\r'));
        }
    }
}
