<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../src/Cordis.Clr/Cordis.Clr.csproj" />
    <Compile Include="../HostProgram.cs" Link="Program.cs" />
  </ItemGroup>
</Project>
